# Generated by Django 3.2.4 on 2021-06-02 17:34

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=50, verbose_name='Website url')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
            options={
                'verbose_name': '_Основные настройки',
                'verbose_name_plural': '_Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория сырья',
                'verbose_name_plural': 'Категории сырья',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('discount', models.IntegerField(blank=True, verbose_name='Скидка')),
                ('pay_type', models.BooleanField(verbose_name='Наличные')),
                ('cost', models.IntegerField(verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Примечание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('color', colorfield.fields.ColorField(default='#6c757d', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'verbose_name': 'Состав заказа',
                'verbose_name_plural': 'Состав заказа',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('units', models.CharField(max_length=50, verbose_name='Единицы измерения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.materialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Сырье',
                'verbose_name_plural': 'Сырье',
            },
        ),
        migrations.CreateModel(
            name='Sostav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.material')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Состав',
                'unique_together': {('product_id', 'material_id')},
            },
        ),
    ]
